import os
from jinja2 import Environment, FileSystemLoader
from config import REPORTS_DIR

TEMPLATE_STR = """# Cybercrime Reconnaissance Report
*Generated by automated domain scanner.*

{% for result in results %}
## Domain: {{ result.domain }}
**URL Visited**: `{{ result.data.url }}`
**Emulated Device**: `{{ result.data.device_emulated }}`
**Proxy**: `{{ result.data.proxy_used }}`

{% if result.data.error %}
**Status**: ❌ Error - {{ result.data.error }}
{% else %}
**Status**: ✅ Successfully Scanned
{% endif %}

{% if result.analysis_data.caption %}
### Capture: {{ result.analysis_data.caption }}
{% if result.data.screenshot_path %}
![Screenshot of {{ result.domain }}](./screenshots/{{ result.domain }}.png)
{% endif %}
{% endif %}

### Analyst Assessment
{{ result.analysis_data.analysis }}

### Network Indicators
* **Downloads Intercepted**: {{ result.data.downloads_detected | length }}
{% for dll in result.data.downloads_detected %}
  - `{{ dll }}`
{% endfor %}
* **Suspicious Requests**: {{ result.data.suspicious_requests | length }}
{% for req in result.data.suspicious_requests %}
  - `{{ req }}`
{% endfor %}

---
{% endfor %}
"""

class MarkdownReporter:
    def __init__(self):
        os.makedirs(REPORTS_DIR, exist_ok=True)
        self.report_path = os.path.join(REPORTS_DIR, "report.md")

    def generate(self, combined_results: list):
        """Generates a markdown report from the combined scanner and analyzer data."""
        
        # We use Jinja2 fromstring for simplicity without needing an external template file
        env = Environment()
        template = env.from_string(TEMPLATE_STR)
        
        output = template.render(results=combined_results)
        
        with open(self.report_path, "w", encoding="utf-8") as f:
            f.write(output)
            
        return self.report_path
