import os
from jinja2 import Environment, FileSystemLoader
from config import REPORTS_DIR


import os
from jinja2 import Environment, FileSystemLoader
from config import REPORTS_DIR

TEMPLATE_STR_MD = """# Cyber Threat Intelligence Report
**Generated by Automated Reconnaissance Pipeline**

{% for result in results %}
## 🚨 Target Profile: `{{ result.domain }}`

| Telemetry | Details |
| :--- | :--- |
| **Analyzed URL** | `{{ result.data.url }}` |
| **Emulated Profile**| `{{ result.data.device_emulated }}` |
| **Proxy Gateway** | `{{ result.data.proxy_used }}` |
| **Status** | {% if result.data.error %}❌ `{{ result.data.error }}`{% else %}✅ Successfully captured & analyzed{% endif %} |

{% if not result.data.error %}
### I. Executive Summary
> {{ result.analysis_data.executive_summary }}

### II. Core Visual Evidence

{% if result.analysis_data.threat_indicators %}
{% for indicator in result.analysis_data.threat_indicators %}
**Indicator {{ loop.index }}: {{ indicator.type }}**
> {{ indicator.description }}

{% if indicator.local_crop_path %}
![Indicator {{ loop.index }}](./screenshots/crops/{{ indicator.local_crop_path | basename }})
{% endif %}

{% endfor %}
{% else %}
*No critical spatial indicators bounded by AI.*
{% endif %}

#### Full-Page Snapshot Overview
![Full Capture of {{ result.domain }}](./screenshots/{{ result.data.screenshot_path | basename }})

---

### III. Technical Analysis
{{ result.analysis_data.technical_analysis }}

### IV. Network & Payload Indicators (IoCs)

**Downloads Intercepted**: `{{ result.data.downloads_detected | length }}`
{% for dll in result.data.downloads_detected %}
- ⚠️ Target: `{{ dll }}`
{% else %}
- *No suspicious auto-downloads detected during dynamic execution.*
{% endfor %}

**Suspicious API/File Requests**: `{{ result.data.suspicious_requests | length }}`
{% for req in result.data.suspicious_requests %}
- 🔴 Request: `{{ req }}`
{% else %}
- *No recognized malicious endpoints called in the background.*
{% endfor %}
{% endif %}

---

{% endfor %}
"""

TEMPLATE_STR_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cyber Threat Intelligence Report</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg-color: transparent;
            --card-bg: rgba(22, 28, 45, 0.7);
            --glass-border: rgba(255, 255, 255, 0.08);
            --accent: #00ff88;
            --accent-glow: rgba(0, 255, 136, 0.3);
            --danger: #ff4757;
            --warning: #ffa502;
            --text-primary: #f1f5f9;
            --text-secondary: #94a3b8;
        }
        body {
            background-color: var(--bg-color);
            color: var(--text-primary);
            font-family: 'Inter', -apple-system, sans-serif;
            margin: 0;
            padding: 20px;
        }
        h1, h2, h3, h4 { color: #fff; }
        .container { max-width: 1200px; margin: 0 auto; }
        
        .dashboard-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-bottom: 40px; }
        .stat-card { background: var(--card-bg); border: 1px solid var(--glass-border); border-radius: 12px; padding: 20px; text-align: center; backdrop-filter: blur(10px); }
        .stat-card h3 { margin: 0; color: var(--text-secondary); font-size: 0.85rem; text-transform: uppercase; letter-spacing: 1px; }
        .stat-card .value { font-size: 2.2rem; font-weight: 700; margin: 10px 0 0; color: var(--text-primary); }
        
        .target-card { background: var(--card-bg); border: 1px solid var(--glass-border); border-radius: 12px; padding: 25px; margin-bottom: 30px; backdrop-filter: blur(10px); box-shadow: 0 4px 20px rgba(0,0,0,0.15); }
        .target-card h2 { margin-top: 0; border-bottom: 1px solid var(--glass-border); padding-bottom: 15px; color: #fff; font-size: 1.4rem; display: flex; align-items: center; gap: 10px; }
        
        .telemetry-table { width: 100%; border-collapse: collapse; margin-bottom: 25px; font-size: 0.9rem; }
        .telemetry-table th, .telemetry-table td { text-align: left; padding: 10px 15px; border-bottom: 1px solid var(--glass-border); }
        .telemetry-table th { color: var(--text-secondary); font-weight: 600; width: 30%; }
        
        .exec-summary { background: rgba(0, 255, 136, 0.05); border-left: 4px solid var(--accent); padding: 15px 20px; border-radius: 0 8px 8px 0; margin-bottom: 25px; line-height: 1.6; font-size: 0.95rem; }
        
        .evidence-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 20px; margin-bottom: 30px; }
        .evidence-card { background: rgba(0,0,0,0.3); border: 1px solid rgba(255, 71, 87, 0.3); border-radius: 8px; overflow: hidden; }
        .evidence-header { background: rgba(255, 71, 87, 0.1); padding: 10px 15px; font-weight: 600; font-size: 0.9rem; color: #ff6b81; border-bottom: 1px solid rgba(255, 71, 87, 0.2); }
        .evidence-body { padding: 15px; }
        .evidence-body p { margin-top: 0; font-size: 0.9rem; line-height: 1.5; color: #cbd5e1; }
        .evidence-img { width: 100%; border-radius: 4px; border: 1px solid var(--glass-border); }
        
        .ioc-section { margin-top: 25px; padding-top: 20px; border-top: 1px dashed var(--glass-border); }
        .ioc-list { list-style: none; padding: 0; margin: 0 0 15px 0; }
        .ioc-list li { background: rgba(0,0,0,0.2); padding: 8px 12px; border-radius: 6px; margin-bottom: 8px; font-family: monospace; font-size: 0.85rem; display: flex; align-items: center; gap: 10px; border: 1px solid var(--glass-border); word-break: break-all; }
        .ioc-badge { background: var(--danger); color: white; padding: 2px 6px; border-radius: 4px; font-size: 0.7rem; font-weight: bold; flex-shrink: 0; }
        .ioc-badge.http { background: var(--warning); color: #000; }
        
        .source-image-btn { display: inline-block; background: transparent; color: #74b9ff; border: 1px solid #74b9ff; padding: 8px 16px; border-radius: 6px; text-decoration: none; font-size: 0.9rem; font-weight: 600; cursor: pointer; transition: 0.2s; }
        .source-image-btn:hover { background: rgba(116, 185, 255, 0.1); }
    </style>
</head>
<body>
    <div class="container">
        
        <!-- Dashboard Stats -->
        <div class="dashboard-grid">
            <div class="stat-card">
                <h3>Total Targets Scanned</h3>
                <div class="value">{{ results|length }}</div>
            </div>
            <div class="stat-card">
                <h3>Successful Captures</h3>
                <div class="value" style="color: #74b9ff;">{{ results|selectattr('data.error', 'none')|list|length }}</div>
            </div>
            <div class="stat-card">
                <h3>Threat Indicators</h3>
                <div class="value" style="color: var(--danger);">
                    {% set count = namespace(val=0) %}
                    {% for r in results %}
                        {% if not r.data.error and r.analysis_data.threat_indicators %}
                            {% set count.val = count.val + r.analysis_data.threat_indicators|length %}
                        {% endif %}
                    {% endfor %}
                    {{ count.val }}
                </div>
            </div>
        </div>

        {% for result in results %}
        <div class="target-card">
            <h2>
                {% if result.data.error %}⚠️{% else %}🚨{% endif %} 
                {{ result.domain }}
            </h2>
            
            <table class="telemetry-table">
                <tr><th>Analyzed URL</th><td><a href="{{ result.data.url }}" target="_blank" style="color: #74b9ff; text-decoration: none;">{{ result.data.url }}</a></td></tr>
                <tr><th>Emulated Profile</th><td>{{ result.data.device_emulated }}</td></tr>
                <tr><th>Proxy Gateway</th><td>{{ result.data.proxy_used }}</td></tr>
                <tr><th>Status</th>
                    <td>
                        {% if result.data.error %}
                        <span style="color: var(--danger); font-weight: 600;">❌ {{ result.data.error }}</span>
                        {% else %}
                        <span style="color: var(--accent); font-weight: 600;">✅ Successfully captured & isolated</span>
                        {% endif %}
                    </td>
                </tr>
            </table>

            {% if not result.data.error %}
            <div class="exec-summary">
                <strong style="display: block; margin-bottom: 5px; color: #fff;">Executive Summary:</strong>
                {{ result.analysis_data.executive_summary }}
            </div>

            <h3 style="margin-top: 30px; font-size: 1.05rem; border-bottom: 1px solid var(--glass-border); padding-bottom: 8px;">Deep Technical Analysis</h3>
            <p style="color: #cbd5e1; line-height: 1.6; margin-bottom: 25px; font-size: 0.95rem;">{{ result.analysis_data.technical_analysis }}</p>

            <h3 style="margin-top: 30px; font-size: 1.05rem; border-bottom: 1px solid var(--glass-border); padding-bottom: 8px;">Visual Evidence</h3>
            {% if result.analysis_data.threat_indicators %}
            <div class="evidence-grid">
                {% for indicator in result.analysis_data.threat_indicators %}
                <div class="evidence-card">
                    <div class="evidence-header">Indicator {{ loop.index }}: {{ indicator.type }}</div>
                    <div class="evidence-body">
                        <p>{{ indicator.description }}</p>
                        {% if indicator.local_crop_path %}
                        <img class="evidence-img" src="./screenshots/crops/{{ indicator.local_crop_path | basename }}" alt="Evidence thumbnail">
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <p style="color: var(--text-secondary); font-style: italic; font-size: 0.9rem;">No specific spatial indicators identified by AI vision.</p>
            {% endif %}

            <div class="ioc-section">
                <h3 style="font-size: 1.05rem; margin-bottom: 15px;">Network & Payload Indicators (IoCs)</h3>
                
                <h4 style="font-size: 0.9rem; color: var(--text-secondary); margin-bottom: 10px;">Downloads Intercepted: {{ result.data.downloads_detected | length }}</h4>
                {% if result.data.downloads_detected %}
                <ul class="ioc-list">
                    {% for dll in result.data.downloads_detected %}
                    <li><span class="ioc-badge">FILE</span> {{ dll }}</li>
                    {% endfor %}
                </ul>
                {% else %}
                <p style="color: var(--text-secondary); font-size: 0.85rem; font-style: italic; margin-bottom: 20px;">No suspicious downloads detected.</p>
                {% endif %}

                <h4 style="font-size: 0.9rem; color: var(--text-secondary); margin-bottom: 10px; margin-top: 20px;">Suspicious API Requests: {{ result.data.suspicious_requests | length }}</h4>
                {% if result.data.suspicious_requests %}
                <ul class="ioc-list">
                    {% for req in result.data.suspicious_requests %}
                    <li><span class="ioc-badge http">HTTP</span> {{ req }}</li>
                    {% endfor %}
                </ul>
                {% else %}
                <p style="color: var(--text-secondary); font-size: 0.85rem; font-style: italic;">No anomalous network calls intercepted.</p>
                {% endif %}
            </div>
            
            <details style="margin-top: 25px;">
                <summary class="source-image-btn">View High-Resolution Capture</summary>
                <div style="margin-top: 15px; text-align: center;">
                    <img src="./screenshots/{{ result.data.screenshot_path | basename }}" style="max-width: 100%; border-radius: 8px; border: 1px solid var(--glass-border);">
                </div>
            </details>

            {% endif %}
        </div>
        {% endfor %}
    </div>
</body>
</html>
"""

class MarkdownReporter:
    def __init__(self):
        os.makedirs(REPORTS_DIR, exist_ok=True)
        self.report_md_path = os.path.join(REPORTS_DIR, "report.md")
        self.report_html_path = os.path.join(REPORTS_DIR, "report.html")

    def generate(self, combined_results: list):
        """Generates both a markdown report and a stunning HTML report."""
        env = Environment()
        env.filters['basename'] = os.path.basename
        
        # Generate Markdown
        template_md = env.from_string(TEMPLATE_STR_MD)
        output_md = template_md.render(results=combined_results)
        with open(self.report_md_path, "w", encoding="utf-8") as f:
            f.write(output_md)
            
        # Generate HTML
        template_html = env.from_string(TEMPLATE_STR_HTML)
        output_html = template_html.render(results=combined_results)
        with open(self.report_html_path, "w", encoding="utf-8") as f:
            f.write(output_html)
            
        return self.report_html_path  # We return html_path as the primary presentation file now

