import os
from jinja2 import Environment, FileSystemLoader
from config import REPORTS_DIR

TEMPLATE_STR = """# Cyber Threat Intelligence Report
**Generated by Automated Reconnaissance Pipeline**
<br>

{% for result in results %}
## 🚨 Target Profile: `{{ result.domain }}`

| Telemetry | Details |
| :--- | :--- |
| **Analyzed URL** | `{{ result.data.url }}` |
| **Emulated Profile**| `{{ result.data.device_emulated }}` |
| **Proxy Gateway** | `{{ result.data.proxy_used }}` |
| **Status** | {% if result.data.error %}❌ `{{ result.data.error }}`{% else %}✅ Successfully captured & analyzed{% endif %} |

{% if not result.data.error %}
### I. Executive Summary
> {{ result.analysis_data.executive_summary }}

### II. Core Visual Evidence

{% if result.analysis_data.threat_indicators %}
<div style="display:flex; flex-wrap:wrap; gap:10px;">
{% for indicator in result.analysis_data.threat_indicators %}
<details open>
  <summary><b>Indicator {{ loop.index }}: {{ indicator.type }}</b></summary>
  <blockquote>{{ indicator.description }}</blockquote>
  {% if indicator.local_crop_path %}
  <img src="./screenshots/crops/{{ indicator.local_crop_path | basename }}" width="400" style="border:1px solid red;">
  {% endif %}
</details>
{% endfor %}
</div>
{% else %}
*No critical spatial indicators bounded by AI.*
{% endif %}

#### Full-Page Snapshot Overview
<details>
  <summary>Click to view the full resolution capture of {{ result.domain }}</summary>
  <img src="./screenshots/{{ result.data.screenshot_path | basename }}" width="600" style="border: 1px solid #333;">
</details>

---

### III. Technical Analysis
{{ result.analysis_data.technical_analysis }}

### IV. Network & Payload Indicators (IoCs)

**Downloads Intercepted**: `{{ result.data.downloads_detected | length }}`
{% for dll in result.data.downloads_detected %}
- ⚠️ Target: `{{ dll }}`
{% else %}
- *No suspicious auto-downloads detected during dynamic execution.*
{% endfor %}

**Suspicious API/File Requests**: `{{ result.data.suspicious_requests | length }}`
{% for req in result.data.suspicious_requests %}
- 🔴 Request: `{{ req }}`
{% else %}
- *No recognized malicious endpoints called in the background.*
{% endfor %}
{% endif %}

<br><br>
{% endfor %}
"""

class MarkdownReporter:
    def __init__(self):
        os.makedirs(REPORTS_DIR, exist_ok=True)
        self.report_path = os.path.join(REPORTS_DIR, "report.md")

    def generate(self, combined_results: list):
        """Generates a markdown report from the combined scanner and analyzer data."""
        
        # We use Jinja2 fromstring for simplicity without needing an external template file
        env = Environment()
        env.filters['basename'] = os.path.basename
        template = env.from_string(TEMPLATE_STR)
        
        output = template.render(results=combined_results)
        
        with open(self.report_path, "w", encoding="utf-8") as f:
            f.write(output)
            
        return self.report_path
